DROP SCHEMA IF EXISTS ESAMEPO;
CREATE SCHEMA ESAMEPO;

USE ESAMEPO;

DROP TABLE IF EXISTS UTENTI;

CREATE TABLE UTENTI(
	NOME char(20),
    COGNOME char(20),
    USERNAME char(10) PRIMARY KEY,
    TIPO smallint(1),
    PW char(10));
    
DROP TABLE IF EXISTS CONTO;
    
CREATE TABLE CONTO(
	USERNAME CHAR(10) PRIMARY KEY,
    SALDO DOUBLE,
    FOREIGN KEY (USERNAME) REFERENCES UTENTI(USERNAME) ON UPDATE CASCADE
    );
    

    
    
    